# Generated by Django 5.2 on 2025-09-10 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('important', models.BooleanField()),
                ('creation_date', models.DateField(default=datetime.date(2025, 9, 10))),
                ('deadline_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
